version: '3.8'

services:
  spring-boot-app:
    image: akramhn16/achat
    container_name: achat_springboot
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
    restart: always

  mysql-db:
    image: mysql:5.6
    container_name: mysql_achat
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: